### PR TITLE
addCamera and addMicrophone allow constraints

### PR DESCRIPTION
**Pull request by mattapperson**
This commit allows a constraints object to be passed in as the first param to allow specific cameras or mics to be selected.

### CODE REVIEW

**Comment by ZuSe** [comment]
It should also work with all webrtc-contraint attributes, shouldn't it?

**Comment by mattapperson** [comment]
It should, yes. I'm using it to switch between shared desktop and a camera in an electron app

**Comment by ZuSe** [comment]
Ok. What I miss atm are the resolution and frame rate constraints that were possible to put in when initializing the localMedia object with the conversations api. This option should be back with your commit :)

**Comment by mattapperson** [comment]
yup 😊

**Comment by mattapperson** [comment]
@markandrus is there a CLA I need to sign?

**Comment by markandrus** [comment]
@mattapperson thanks for the PR! There's no CLA to sign (I'm not sure if we need one or not...). The team will take a look at your changes later today.

**Comment by ryan-rowland** [comment]
LGTM 👍 

Not an action item for this PR, but seeing this change duplicated for audio & video prompted me to compare `addCamera` and `addMicrophone`. Since these are essentially doing the same thing for two different types of tracks, maybe we could consider DRYing it up. @markandrus

**Comment by mattapperson** [comment]
@ryan-rowland I was just thinking the same when creating this PR

**Comment by manjeshbhargav** [comment]
LGTM

**Comment by mattapperson** [comment]
Woot! Thanks guys!

**Pull request merged**
