### PR TITLE
VIDEO-8939 - Migrating twilio/webrtc

### PR DESCRIPTION
**Pull request by PikaJoyce**
JIRA Ticket: [VIDEO-8939](https://issues.corp.twilio.com/browse/VIDEO-8939)

This PR is for the first phase of webrtc files being migrated over within the SDK. This should subsequently fix [VIDEO-8609](https://issues.corp.twilio.com/browse/VIDEO-8609) as well. 

I have verified that webpack 5 will compile the sdk successfully after folding in twilio/webrtc. See image below
image

**Contributing to Twilio**

> All third party contributors acknowledge that any contributions they provide will be made under the same open source license that the open source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

### Before review
* [ ] Updated CHANGELOG.md if necessary
* [ ] Added unit tests if necessary
* [ ] Updated affected documentation
* [x] Verified locally with `npm test`
* [x] Manually sanity tested running locally
* [x] Included screenshot as PR comment (if needed)
* [ ] Ready for review

### CODE REVIEW

**Comment by makarandp0** [comment]
This is great new @PikaJoyce  -  Did the fix require using separate modules for util and events? 

Since this PR adds tons of new files, I think its hard to review as it is, we mainly want to review any edits that you made to the twilio/webrtc files, and any existing twilio-video files. Can you split this into two commits

commit 1: just copy files of all webrtc files we do not need to review this part, and Its okay if the build does not work after this commit.
commit 2: any edits on top of commit 1.

**Comment by makarandp0** [comment]
Nice @PikaJoyce! 
I think with twilio/webrtc moving over,  we need to reorganize tests - not all webrtc tests need to run as part of every PR (and not all tests need to run in every combination of browser/bver) But that can be done as a separate PR - Please file a task for this. 

but this PR looks good to me.

**Review by makarandp0 — APPROVED** [review]

**Comment by xtianjohns** [comment]
Hey @makarandp0, @PikaJoyce, @charliesantos just a note here - I don't think that the `events` and `util` polyfill problem is solved. I think for webpack this can likely work because transforms will supply the correct browser shims for them.

However, for rollup, this is still a major problem. I think this could be being tracked in VIDEO-6516 but I'm not really sure. Gitlab issue is #1347. Until twilio-video stops depending on the polyfills or some other solution is reached, the only way to bundle the SDK into some other output format is to use webpack.

**Comment by PikaJoyce** [comment]
Hi @xtianjohns!

Thanks for the comment. We realize that for snowpack/rollup that this issue still exists. We currently have a ticket to address this specific issue (VIDEO-3612). We hope to resolve this issue for all users soon. 

We appreciate your patience! Thank you!

Best,
Joyce

**Pull request merged**
