### PR TITLE
Add LocalDataTrack example to JSDoc

### PR DESCRIPTION
**Pull request by markandrus**
@manjeshbhargav not quite sure about this example--it's rather large, but seems like we really want to explain both halves (local and remote).

screen shot 2017-10-12 at 3 00 43 pm

### CODE REVIEW

**Comment by manjeshbhargav** [comment]
@markandrus How about this example:

```javascript
var Video = require('twilio-video');
var localDataTrack = new Video.LocalDataTrack();

Video.connect('my-token', {
  name: 'my-room',
  tracks: [localDataTrack]
}).then(function(room) {
  room.on('participantConnected', function(participant) {
    localDataTrack.send('Welcome!');
  });
});

Video.connect('other-token', {
  name: 'my-room'
}).then(function(room) {
  room.on('trackSubscribed', function(track, participant) {
    track.on('message', function(message) {
      console.log(message); // Welcome!
    });
  });
});
```

**Comment by markandrus** [comment]
@manjeshbhargav looks good--i like that it's a bit more symmetric and has a nice kind of sub-narrative... one concern though: the DataTracks aren't completely reliable/timing sensitive. If you wrote a test for sending a single message, I'm not sure it would succeed. Nevertheless, maybe this is sufficient for an example?

**Comment by manjeshbhargav** [comment]
@markandrus You could delay `localDataTrack.send()` by a second or two. I think that would work.

**Comment by markandrus** [comment]
@manjeshbhargav i updated to your example

**Comment by manjeshbhargav** [comment]
+1

**Pull request merged**
