### PR TITLE
adds getVersion and IsSupported checks for audio plugin

### PR DESCRIPTION
**Pull request by makarandp0**
Audio Plugins are now required to support getVersion and isSupported functions. Those will be used by SDK when loading the audio plugins. When version or isSupported mismatch is found SDK will not use noise cancellation plugin.

**Contributing to Twilio**

> All third party contributors acknowledge that any contributions they provide will be made under the same open source license that the open source project is provided under.

- [ ] I acknowledge that all my contributions will be made under the project's license.

### Description

A description of what this PR does.

### Before review
* [ ] Updated CHANGELOG.md if necessary
* [ ] Added unit tests if necessary
* [ ] Updated affected documentation
* [ ] Verified locally with `npm test`
* [ ] Manually sanity tested running locally
* [ ] Included screenshot as PR comment (if needed)
* [ ] Ready for review

### CODE REVIEW

**Review by charliesantos — COMMENTED** [review]
@makarandp0 how does this work if the sdk supports multiple versions?

**Comment by makarandp0** [comment]
> @makarandp0 how does this work if the sdk supports multiple versions?

@charliesantos, SDK will require that major version must match and minor version must be greater than supported minor version. As long as those parameters work, sdk can support multiple minor versions.

**Review by charliesantos — COMMENTED** [review]
I have a few concerns on this
- Since the new assets file are for testing only, I don't think they belong in the root directory. Maybe put them inside tests folder?
- The way I understand it, if some customers update the sdk that has a new minor version support, it breaks all customers that are still on older version of the plugin. Should it be backwards compatible? That is, only throw the error if the customer updated the plugin but did not update the video sdk
- Do we really need to do this? If we're using semver for both the sdk and the plugin, the rules are already implied correct?

@manjeshbhargav can you chime in?

**Comment by makarandp0** [comment]
got +1 from @charliesantos offline: https://twilio.slack.com/archives/C01LMDCUF37/p1660579253767719?thread_ts=1660253627.569549&cid=C01LMDCUF37

**Pull request merged**
