### PR TITLE
adapter.js known issue + update dev dependency

### PR DESCRIPTION
**Pull request by makarandp0**
**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [ ] I acknowledge that all my contributions will be made under the project's license.

### CODE REVIEW

**Review by manjeshbhargav — CHANGES_REQUESTED** [review]
@makarandp0 I think the title and description need to be about the SDK behavior that affects the customer, and not the internal behavior of webrtc.

**Comment by anna-vasilko** [comment]
@makarandp0 Please correct minor typo (capital P after comma). The issue description all in one sentence is a bit bulky, could be good to split/re-phrase.

**Comment by makarandp0** [comment]
@manjeshbhargav @anna-vasilko - I have updated the title and description of issue a bit. Please take another look.

**Review by anna-vasilko — APPROVED** [review]
LGTM

**Pull request merged**
